// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydmxplmusxcgwnuayufb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkbXhwbG11c3hjZ3dudWF5dWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MTY5OTUsImV4cCI6MjA3NzE5Mjk5NX0.n48DLXAGUqRwY3x7hd8-ZANcIBAN_8E5OfDfG2Mpmlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});